@host = http://localHost:5000

###
GET {{host}}

### 注册
POST {{host}}/users
Content-Type: application/json

{
  "data": {
  "_id":1,
  "_username":"aaa",
  "_password":"123456","_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjQyMzAyNTM2LCJleHAiOjE2NDIzMDYxMzZ9._yN4tcinjswvFBbKLYNGM6VdrtBCYvHFIfobtdMD3yM",
  "_power":0,
  "_realname":"周易",
  "_gender":0,
  "_major":" 男",
  "_grade":"软件工程",
  "_class":"2018",
  "_stuId":"14",
  "_email":"",
  "_phone":"",
  "_avatarUrl":""
}
}


### 登录
POST {{host}}/users/login
Content-Type: application/json

{
  "username": "aaa",
  "password": "123456"
}