@host = http://localHost:5000

###
GET {{host}}

### 注册
POST {{host}}/users
Content-Type: application/json

{
  "data": {
  "id":2,
  "user_name":"aaa",
  "password":"123456","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjQyMzAyNTM2LCJleHAiOjE2NDIzMDYxMzZ9._yN4tcinjswvFBbKLYNGM6VdrtBCYvHFIfobtdMD3yM",
  "power":0,
  "real_name":"周壹",
  "gender":"女",
  "major":"软件工程",
  "grade":"2018",
  "class":"2",
  "stu_id":"8003118329",
  "email":"",
  "phone":"",
  "avatar_url":""
}
}


### 登录
POST {{host}}/users/login
Content-Type: application/json

{
  "username": "aaa",
  "password": "123456"
}


### 修改个人信息
PATCH {{host}}/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjQzNTk2ODc0LCJleHAiOjE2NDM2MDA0NzR9.IKIk3-tLWn6Azc5en5wuFig0Yqa1FYb9OznOBCJ01jg

{
  "data": {
  "id":2,
  "user_name":"aaa",
  "password":"123456","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYSIsInBhc3N3b3JkIjoiMTIzNDU2IiwiaWF0IjoxNjQyMzAyNTM2LCJleHAiOjE2NDIzMDYxMzZ9._yN4tcinjswvFBbKLYNGM6VdrtBCYvHFIfobtdMD3yM",
  "power":0,
  "real_name":"周壹",
  "gender":"女",
  "major":"软件工程",
  "grade":"2018",
  "class":"2",
  "stu_id":"8003118329",
  "email":"",
  "phone":"",
  "avatar_url":""
}
}


### 修改密码
PATCH {{host}}/users/psd
Content-Type: application/json

{
  "username": "aaa",
  "oldPassword": "12345",
  "newPassword": "654321"
}


### 新建社团
POST {{host}}/societies
Content-Type: application/json

{
  "society": {
    "id":0,
    "name":"舞蹈社",
    "u_id": 2,
    "president":"盛贰",
    "founder":"李弥",
    "classification":"文艺爱好","founding_date":"2002-04-30",
    "introduction":"本社团以弘扬民族书法艺术为宗旨，以提高社员的书写技能，促进校园文化建设为目标。了解书法基本知识，提高社员书法水平。养成良好写字习惯。培养学生爱好书法的兴趣，初步感受书法的艺术美。",
    "ratify":0,
    "recruit_eligible":0
  },
  "application": {
    "id": 0, 
    "type":1, 
    "associated_id":0, 
    "u_id":2, 
    "title":"创立社团", 
    "content":"", 
    "img_urls":"", 
    "file_urls":"", 
    "state":0, 
    "submit_time":"2022-02-05 12:00:00", 
    "review_time": "", 
    "review_opinion":""
  }
}


### 修改社团信息
PATCH {{host}}/societies
Content-Type: application/json

{
  "data": {
    "id":5,
    "name":"舞蹈社",
    "u_id": 2,
    "president":"林散",
    "founder":"李弥",
    "classification":"文艺爱好","founding_date":"2002-04-30",
    "introduction":"本社团以弘扬民族书法艺术为宗旨，以提高社员的书写技能，促进校园文化建设为目标。了解书法基本知识，提高社员书法水平。养成良好写字习惯。培养学生爱好书法的兴趣，初步感受书法的艺术美。",
    "ratify":0,
    "recruit_eligible":0
  }
}

### 修改社团招新权限
PATCH {{host}}/societies/recruit
Content-Type: application/json

{
  "societyId": 7,
  "recruit": 1
}



### 删除社团
DELETE {{host}}/societies
Content-Type: application/json

{
  "data": 7
}

### 获取社团信息
GET {{host}}/societies?id=2


### 新建部门
POST {{host}}/departments
Content-Type: application/json

{
  "department": {"id":null,"name":"技术部","s_id":6,"founding_date":"2022-02-10", "minister": "陈零了", "introduction":"本部门由水平较高的棋手组成，负责研究学习围棋、精进棋艺，给其他部门授艺，以及对外赛事主力。","member_num":0,"ratify":0},
  "application": {
    "id": null, "type":2, "associated_id":null, "u_id":2, "title":"创立部门", "content":"", "file_urls":"", "img_urls":"", "state":0, "submit_time":"2022-02-10 10:28:00", "review_time": "", "review_opinion":""
  }
}


### 修改部门
PATCH {{host}}/departments
Content-Type: application/json

{
  "data": {"id":5,"name":"策划部","s_id":3,"founding_date":"2002-04-30", "minister": "陈菱袅", "introduction":"本部门负责策划本社团的各种活动","member_num":0,"ratify":0}
}

### 获取部门信息
GET {{host}}/departments?id=3


### 添加成员
POST {{host}}/members
Content-Type: application/json

{
  "data": {
    "id": 0,
    "u_id": 2,
    "s_id": 3,
    "d_id": 5,
    "position": "部长",
    "join_time": "2004-10-01 00:00:00"
  }
}

### 修改成员
PATCH {{host}}/members
Content-Type: application/json

{
  "data": {
    "id": 2,
    "u_id": 2,
    "s_id": 3,
    "d_id": 5,
    "position": "部委",
    "join_time": "2004-10-01 00:00:00"
  }
}

### 获取成员信息
GET {{host}}/members?id=3

### 删除成员
DELETE {{host}}/members
Content-Type: application/json

{
  "data": 2
}


### 添加财务信息
POST {{host}}/financialinfos
Content-Type: application/json

{
  "data": {
    "id": 0,
    "s_id": 3,
    "d_id": 5,
    "handler": "王小盼",
    "type": 0,
    "amount": 121.8,
    "record_time": "2022-02-13 12:15:00",
    "remark": "买入两个沙包"
  }
}

### 修改财务信息
PATCH {{host}}/financialinfos
Content-Type: application/json

{
  "data": {
    "id": 2,
    "s_id": 3,
    "d_id": 5,
    "handler": "王小盼",
    "type": 0,
    "amount": 221.88,
    "record_time": "2022-02-13 12:15:00",
    "remark": "买入两个沙包"
  }
}

### 获取财务信息
GET {{host}}/financialinfos?id=3

### 按年获取财务信息
GET {{host}}/financialinfos/export?id=3&year=2022

### 删除财务信息
DELETE {{host}}/financialinfos
Content-Type: application/json

{
  "data": 3
}



### 添加活动
POST {{host}}/activities
Content-Type: application/json

{
  "activity": {
    "id": null,
    "name": "晨练",
    "s_id": 3,
    "content": "为期一周的晨练活动，和武术社的小伙伴们一起强身健体吧！",
    "place": "田径场",
    "start_time": "2022-02-14 7:00:00",
    "end_time": "2022-02-14 8:00:00",
    "state": 0,
    "ratify": 0
  },
  "application": {
    "id": null, "type":3, "associated_id":null, "u_id":2, "title":"开展活动", "content":"开展晨练活动，为期一周", "file_urls":"", "img_urls":"", "state":0, "submit_time":"2022-02-13 14:39:00", "review_time": "", "review_opinion":""
  }
}

### 修改活动信息
PATCH {{host}}/activities
Content-Type: application/json

{
  "data": {
    "id": 3,
    "name": "晨练",
    "s_id": 3,
    "content": "为期一周的晨练活动，和武术社的小伙伴们一起强身健体吧！",
    "place": "田径场",
    "start_time": "2022-02-14 7:00:00",
    "end_time": "2022-02-20 8:00:00",
    "state": 0,
    "ratify": 0
  }
}

### 获取活动信息
GET {{host}}/activities?id=0


### 删除活动
DELETE {{host}}/activities
Content-Type: application/json

{
  "data": 2
}


### 参加活动
POST {{host}}/participants
Content-Type: application/json

{
  "userId": 2,
  "activityId": 3
}

### 签到
PATCH {{host}}/participants/state
Content-Type: application/json

{
  "userId": 2,
  "activityId": 3
}

### 发表活动评论
PATCH {{host}}/participants/comments
Content-Type: application/json

{
  "userId": 2,
  "activityId": 3,
  "score": 5,
  "comment": "坚持了一周时间，我感觉自己已经开始养成锻炼的习惯了。"
}

### 获取参与者信息
GET {{host}}/participants?id=3

### 抽奖
PATCH {{host}}/participants/lottery
Content-Type: application/json

{
  "activityId": 3,
  "count": 1,
  "level": 3
}


### 退出活动
DELETE {{host}}/participants
Content-Type: application/json

{
  "userId": 2,
  "activityId": 3
}


### 新建招募信息
POST {{host}}/recruitments
Content-Type: application/json

{
  "data": {
    "id": null,
    "s_id": 6,
    "d_id": 6,
    "recruit_num": 5,
    "requirement": "围棋水平高",
    "start_time": "2022-02-14 7:00:00",
    "end_time": "2022-02-20 19:00:00",
    "state": 0,
    "ratify": 0
  }
}

### 修改招募信息
PATCH {{host}}/recruitments
Content-Type: application/json

{
  "data": {
    "id": 2,
    "s_id": 6,
    "d_id": 6,
    "recruit_num": 4,
    "requirement": "围棋水平高",
    "start_time": "2022-02-14 7:00:00",
    "end_time": "2022-02-20 19:00:00",
    "state": 0,
    "ratify": 0
  }
}

### 获取招募信息
GET {{host}}/recruitments?id=3



### 参加社团招新
POST {{host}}/candidates
Content-Type: application/json

{
  "data": {
    "id": null,
    "u_id": 2,
    "r_id": 2,
    "state": 0,
    "test_score": 80,
    "interview_evaluation": "",
    "interview_score": 0
  }
}

### 修改候选人信息
PATCH {{host}}/candidates
Content-Type: application/json

{
  "candidateId": 2,
  "score": 60,
  "evaluation": "思辨能力未达标",
  "pass": false
}

### 修改候选人状态
PATCH {{host}}/candidates/state
Content-Type: application/json

{
  "candidateId": 2,
  "state": 5
}

### 获取候选人信息
GET {{host}}/candidates?id=2


### 添加新闻
POST {{host}}/news
Content-Type: application/json

{
  "data": {
    "id": 0,
    "contributor": "王小盼",
    "s_id": 6,
    "theme": "元宵比武",
    "outline": "元宵节武术社举办一起团团圆圆，煮汤圆，看表演，比武助兴活动。",
    "content": "",
    "published_time": "2022-02-15 10:56:00"
  }
}

### 修改新闻
PATCH {{host}}/news
Content-Type: application/json

{
  "data": {
    "id": 2,
    "contributor": "王小盼",
    "s_id": 3,
    "theme": "元宵分享",
    "outline": "元宵节武术社成员分享团团圆圆照：煮汤圆、看表演，伙伴们来晒出自己的温馨！",
    "content": "恰逢元宵节，武术社各位成员纷纷晒出了自己家过元宵的“仪式感”。",
    "published_time": "2022-02-15 10:56:00"
  }
}

### 获取新闻
GET {{host}}/news?id=0


### 删除新闻
DELETE {{host}}/news
Content-Type: application/json

{
  "data": 3
}



### 添加申请
POST {{host}}/applications
Content-Type: application/json

{
  "data": {
    "id": null, "type":8, "associated_id":4, "u_id":2, "title":"注销部门", "content":"注销组织部", "file_urls":"", "img_urls":"", "state":0, "submit_time":"2022-02-15 11:34:00", "review_time": "", "review_opinion":""
  }
}


### 获取申请信息
GET {{host}}/applications


### 审批申请
PATCH {{host}}/applications
Content-Type: application/json

{
  "applicationId": 12,
  "associatedId": 4,
  "type": 8,
  "state": 1,
  "opinion": "通过"
}


### 结束招新
PATCH {{host}}/applications/recruit


### 删除申请
DELETE {{host}}/applications
Content-Type: application/json

{
  "data": 13
}